### ISSUE TITLE
Add OOP Online Past Papers here

### ISSUE THREAD

**Issue by chamodshehanka** [SLIITSE/Year2-Sem1#2]
![oop](https://user-images.githubusercontent.com/19349315/57445855-e11a1f80-7270-11e9-9f02-9fbfe88be60d.jpeg)

**Comment by chamodshehanka** [comment]
@dcjc29 oya uda thiyena eka un official ekakda?

**Comment by chamodshehanka** [comment]
![image](https://user-images.githubusercontent.com/19349315/57468062-5ef61f00-72a1-11e9-8b0f-862b7f43c230.png)

**Comment by dcjc29** [comment]
> @dcjc29 oya uda thiyena eka un official ekakda?

Na official ekak nemei.Papers add karaddi question eka witharak danna crop karala

**Comment by chamodshehanka** [comment]
![image](https://user-images.githubusercontent.com/19349315/57484612-1fdac480-72c7-11e9-8d71-bb16013bde53.png)

**Comment by chamodshehanka** [comment]
![image](https://user-images.githubusercontent.com/19349315/57484696-51ec2680-72c7-11e9-9e93-d761b812874e.png)

**Comment by chamodshehanka** [comment]
![image](https://user-images.githubusercontent.com/19349315/57484796-924ba480-72c7-11e9-92ca-ca079072f3e0.png)

**Comment by chamodshehanka** [comment]
![image](https://user-images.githubusercontent.com/19349315/57531127-662b3480-7356-11e9-9dab-cac48f2af7e6.png)
